{
 "title": "Server-PLEX SMART",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "sata1",
   "type": "table",
   "gridPos": { "h": 27, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ID\" or r[\"_field\"] == \"RAW_value\" or r[\"_field\"] == \"current_value\" or r[\"_field\"] == \"threshold_value\" or r[\"_field\"] == \"worst_value\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\" or r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\" or r[\"smart_attribute\"] == \"Command_Timeout\" or r[\"smart_attribute\"] == \"Current_Pending_Sector\" or r[\"smart_attribute\"] == \"End-to-End_Error\" or r[\"smart_attribute\"] == \"Erase_Fail_Count\" or r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\" or r[\"smart_attribute\"] == \"Host_Program_Page_Count\" or r[\"smart_attribute\"] == \"Offline_Uncorrectable\" or r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\" or r[\"smart_attribute\"] == \"Power_Cycle_Count\" or r[\"smart_attribute\"] == \"Power_On_Hours\" or r[\"smart_attribute\"] == \"Program_Fail_Count\" or r[\"smart_attribute\"] == \"RAIN_Success_Recovered\" or r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\" or r[\"smart_attribute\"] == \"Reallocated_Event_Count\" or r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\" or r[\"smart_attribute\"] == \"Reported_Uncorrect\" or r[\"smart_attribute\"] == \"Reserved_Block_Pct\" or r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\" or r[\"smart_attribute\"] == \"Temperature_Celsius\" or r[\"smart_attribute\"] == \"Total_LBAs_Written\" or r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\" or r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\" or r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\" or r[\"smart_attribute\"] == \"Write_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "sata2",
   "type": "table",
   "gridPos": { "h": 27, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ID\" or r[\"_field\"] == \"RAW_value\" or r[\"_field\"] == \"current_value\" or r[\"_field\"] == \"threshold_value\" or r[\"_field\"] == \"worst_value\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\" or r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\" or r[\"smart_attribute\"] == \"Command_Timeout\" or r[\"smart_attribute\"] == \"Current_Pending_Sector\" or r[\"smart_attribute\"] == \"End-to-End_Error\" or r[\"smart_attribute\"] == \"Erase_Fail_Count\" or r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\" or r[\"smart_attribute\"] == \"Host_Program_Page_Count\" or r[\"smart_attribute\"] == \"Offline_Uncorrectable\" or r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\" or r[\"smart_attribute\"] == \"Power_Cycle_Count\" or r[\"smart_attribute\"] == \"Power_On_Hours\" or r[\"smart_attribute\"] == \"Program_Fail_Count\" or r[\"smart_attribute\"] == \"RAIN_Success_Recovered\" or r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\" or r[\"smart_attribute\"] == \"Reallocated_Event_Count\" or r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\" or r[\"smart_attribute\"] == \"Reported_Uncorrect\" or r[\"smart_attribute\"] == \"Reserved_Block_Pct\" or r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\" or r[\"smart_attribute\"] == \"Temperature_Celsius\" or r[\"smart_attribute\"] == \"Total_LBAs_Written\" or r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\" or r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\" or r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\" or r[\"smart_attribute\"] == \"Write_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "SATA1 Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "select": [
      [
       { "params": [ "disk_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" }
     ]
    }
   ]
  },
  {
   "title": "SATA2 Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"disk_status\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" }
     ]
    }
   ]
  },
  {
   "title": "SATA3 Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"disk_status\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "disk_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" }
     ]
    }
   ]
  },
  {
   "title": "sata3",
   "type": "table",
   "gridPos": { "h": 27, "w": 10, "x": 5, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ID\" or r[\"_field\"] == \"RAW_value\" or r[\"_field\"] == \"current_value\" or r[\"_field\"] == \"threshold_value\" or r[\"_field\"] == \"worst_value\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\" or r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\" or r[\"smart_attribute\"] == \"Command_Timeout\" or r[\"smart_attribute\"] == \"Current_Pending_Sector\" or r[\"smart_attribute\"] == \"End-to-End_Error\" or r[\"smart_attribute\"] == \"Erase_Fail_Count\" or r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\" or r[\"smart_attribute\"] == \"Host_Program_Page_Count\" or r[\"smart_attribute\"] == \"Offline_Uncorrectable\" or r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\" or r[\"smart_attribute\"] == \"Power_Cycle_Count\" or r[\"smart_attribute\"] == \"Power_On_Hours\" or r[\"smart_attribute\"] == \"Program_Fail_Count\" or r[\"smart_attribute\"] == \"RAIN_Success_Recovered\" or r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\" or r[\"smart_attribute\"] == \"Reallocated_Event_Count\" or r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\" or r[\"smart_attribute\"] == \"Reported_Uncorrect\" or r[\"smart_attribute\"] == \"Reserved_Block_Pct\" or r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\" or r[\"smart_attribute\"] == \"Temperature_Celsius\" or r[\"smart_attribute\"] == \"Total_LBAs_Written\" or r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\" or r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\" or r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\" or r[\"smart_attribute\"] == \"Write_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Life Remaining",
   "type": "timeseries",
   "description": "RAW value: This value is expressed as a percentage of the average erase count and the rated erase\ncount of the media, which is the percentage of lifetime used as opposed to the Current\nValue which is the percentage of lifetime remaining.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "Sata1_RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (100-distinct(\"RAW_value\")) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Percent_Lifetime_Remain') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2_RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (100-distinct(\"RAW_value\")) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Percent_Lifetime_Remain') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3_RAW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (100-distinct(\"RAW_value\")) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Percent_Lifetime_Remain') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Percent_Lifetime_Remain" }
     ]
    },
    {
     "alias": "Sata1_RAS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Sector_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Reallocated_Sector_Ct" }
     ]
    },
    {
     "alias": "Sata2_RAS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Sector_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Reallocated_Sector_Ct" }
     ]
    },
    {
     "alias": "Sata3_RAS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Sector_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Reallocated_Sector_Ct" }
     ]
    },
    {
     "alias": "Sata1_Reserved",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unused_Rsvd_Blk_Cnt_Tot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Unused_Rsvd_Blk_Cnt_Tot" }
     ]
    },
    {
     "alias": "Sata2_Reserved",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unused_Rsvd_Blk_Cnt_Tot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Unused_Rsvd_Blk_Cnt_Tot" }
     ]
    },
    {
     "alias": "Sata3_Reserved",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unused_Rsvd_Blk_Cnt_Tot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Unused_Rsvd_Blk_Cnt_Tot" }
     ]
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "timeseries",
   "description": "Endurance (TBW in PB) for Micron 5200 ECO is 3.5 Peta-Bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (distinct(\"RAW_value\")*4096) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Total_LBAs_Written') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (distinct(\"RAW_value\")*4096) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Total_LBAs_Written') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (distinct(\"RAW_value\")*4096) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Total_LBAs_Written') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Total_LBAs_Written" }
     ]
    }
   ]
  },
  {
   "title": "Reallocated_Sector_Ct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\")FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Sector_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Sector_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Sector_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Reallocated_Sector_Ct" }
     ]
    }
   ]
  },
  {
   "title": "Reserved_Block_Pct",
   "type": "timeseries",
   "description": "This value is the number of reserved blocks that have been used on the drive",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\")FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reserved_Block_Pct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reserved_Block_Pct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reserved_Block_Pct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Reserved_Block_Pct" }
     ]
    }
   ]
  },
  {
   "title": "Reallocated_Event_Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Event_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Event_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Reallocated_Event_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Reallocated_Event_Count" }
     ]
    }
   ]
  },
  {
   "title": "Erase_Fail_Count",
   "type": "timeseries",
   "description": "This value contains the raw number of ERASE failure events over the lifetime of the device.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Erase_Fail_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Erase_Fail_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Erase_Fail_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Erase_Fail_Count" }
     ]
    }
   ]
  },
  {
   "title": "Write Amplification Factor",
   "type": "timeseries",
   "description": "Write amplification factor (WAF) is a numerical value that represents the amount of data a solid state storage controller has to write in relation to the amount of data that the host’s flash controller has to write.  The numerical value is calculated as a rate by dividing the amount of data written to flash media by the amount of data written by the host.\n\nA write amplification factor of 1 means that 1GB of data was written to the flash host media and the host’s flash controller also wrote 1GB.  A write factor of 1 is ideal, but occurs less frequently as the media gets used and the number of program/erase (P/E) cycles increases.  Program/erase cycles are managed by the device's flash controller, which uses a logical to physical mapping system known as logical block addressing (LBA) to manage data. When data is rewritten, the flash controller writes the new data in a different location and then updates the LBA with the new location. Invalid data continues to reside in the old location and those cells must be erased before they can be written to again. Because each cell can only tolerate a finite number of program/erase cycles before becoming unreliable, the higher the write amplification factor, the closer the media is to end-of-life.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "alias": "Sata1_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Host_Program_Page_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Host_Program_Page_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Host_Program_Page_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Host_Program_Page_Count" }
     ]
    },
    {
     "alias": "Sata1_background",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Bckgnd_Program_Page_Cnt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Bckgnd_Program_Page_Cnt" }
     ]
    },
    {
     "alias": "Sata2_background",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Bckgnd_Program_Page_Cnt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Bckgnd_Program_Page_Cnt" }
     ]
    },
    {
     "alias": "Sata3_background",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Bckgnd_Program_Page_Cnt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Bckgnd_Program_Page_Cnt" }
     ]
    }
   ]
  },
  {
   "title": "Bckgnd Program Page Cnt",
   "type": "timeseries",
   "description": "Average erase count of all good blocks. \nalso known as \"FTL Program Page Count\" Number of NAND pages written by the FTL.\n\nThis value stores the cumulative FTL program page count. This attribute tracks the\nnumber of NAND pages programed by the FTL which are in addition to operations programed by the host. Write amplification factor can be calculated by WAF = (Attrib_247 +\nAttrib_248) / Attrib_247.\n\nWAF = (Host Program Page Count + FTL Program Page Count) / Host Program Page Count",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Bckgnd_Program_Page_Cnt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Bckgnd_Program_Page_Cnt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Bckgnd_Program_Page_Cnt') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Bckgnd_Program_Page_Cnt" }
     ]
    }
   ]
  },
  {
   "title": "Host_Program_Page_Count",
   "type": "timeseries",
   "description": "Number of NAND pages of data written by the host",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Host_Program_Page_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Host_Program_Page_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Host_Program_Page_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Host_Program_Page_Count" }
     ]
    }
   ]
  },
  {
   "title": "Avg Block Erase Count",
   "type": "timeseries",
   "description": "Average erase count of all good blocks",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Avg_Block-Erase_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Avg_Block-Erase_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Avg_Block-Erase_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    }
   ]
  },
  {
   "title": "Command Timeout",
   "type": "timeseries",
   "description": "Upon any HRESET, COMRESET, SRST: adds ac\n\nThis counter is incremented by the number of outstanding commands when the host\nissues a soft reset or a comreset. If the value ever exceeds FFFFFFFFFFFFh, it wraps\naround.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Command_Timeout') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Command_Timeout') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Command_Timeout') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Command_Timeout" }
     ]
    }
   ]
  },
  {
   "title": "End-to-End_Error",
   "type": "timeseries",
   "description": "hat after transferring through the cache RAM data buffer, the parity data between the host and the hard drive did not match.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'End-to-End_Error') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'End-to-End_Error') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'End-to-End_Error') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "End-to-End_Error" }
     ]
    }
   ]
  },
  {
   "title": "Hardware_ECC_Recovered",
   "type": "timeseries",
   "description": "Tracks the total number of bits corrected over the lifetime of\nthe device",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Hardware_ECC_Recovered') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Hardware_ECC_Recovered') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Hardware_ECC_Recovered') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Hardware_ECC_Recovered" }
     ]
    }
   ]
  },
  {
   "title": "Offline_Uncorrectable",
   "type": "timeseries",
   "description": "Uncorrectable error count detected during SMART offline scan\n\nThis value is the cumulative number of unrecoverable read errors found in a background media scan.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Offline_Uncorrectable') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Offline_Uncorrectable') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Offline_Uncorrectable') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Offline_Uncorrectable" }
     ]
    }
   ]
  },
  {
   "title": "Power_Cycle_Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 152 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Power_Cycle_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Power_Cycle_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Power_Cycle_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Power_Cycle_Count" }
     ]
    }
   ]
  },
  {
   "title": "Power_On_Days",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 159 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (distinct(\"RAW_value\")/24) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Power_On_Hours') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (distinct(\"RAW_value\")/24) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Power_On_Hours') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT (distinct(\"RAW_value\")/24) FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Power_On_Hours') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Power_On_Hours" }
     ]
    }
   ]
  },
  {
   "title": "Program_Fail_Count",
   "type": "timeseries",
   "description": "Number of NAND program status failures",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 166 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Program_Fail_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Program_Fail_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Program_Fail_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Program_Fail_Count" }
     ]
    }
   ]
  },
  {
   "title": "RAIN_Success_Recovered",
   "type": "timeseries",
   "description": "The total number of translation units (TU) successfully recovered by Micron's redundant array of independent NAND (RAIN) technology; increments when RAIN successfully recovers user data.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 173 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'RAIN_Success_Recovered') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'RAIN_Success_Recovered') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'RAIN_Success_Recovered') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "RAIN_Success_Recovered" }
     ]
    }
   ]
  },
  {
   "title": "Raw_Read_Error_Rate",
   "type": "timeseries",
   "description": "Raw correctable and uncorrectable read error rate",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\")FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Raw_Read_Error_Rate') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Raw_Read_Error_Rate') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Raw_Read_Error_Rate') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Raw_Read_Error_Rate" }
     ]
    }
   ]
  },
  {
   "title": "SATA_Int_Downshift_Ct",
   "type": "timeseries",
   "description": "Represents the total number of host interface speed downshifts on the SATA link. For\nexample, the SATA link shifts to a lower-generation speed (1.5 Gb/s or 3.0 Gb/s) than\nwhat was previously negotiated (6 Gb/s).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 187 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\")FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'SATA_Int_Downshift_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'SATA_Int_Downshift_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'SATA_Int_Downshift_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "SATA_Int_Downshift_Ct" }
     ]
    }
   ]
  },
  {
   "title": "UDMA_CRC_Error_Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 194 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\")FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'UDMA_CRC_Error_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'UDMA_CRC_Error_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'UDMA_CRC_Error_Count') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "UDMA_CRC_Error_Count" }
     ]
    }
   ]
  },
  {
   "title": "Unexpect_Power_Loss_Ct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 201 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\")FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unexpect_Power_Loss_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unexpect_Power_Loss_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unexpect_Power_Loss_Ct') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Unexpect_Power_Loss_Ct" }
     ]
    }
   ]
  },
  {
   "title": "Unused_Rsvd_Blk_Cnt_Tot",
   "type": "timeseries",
   "description": "Nominal number is 6718 for a Micron 5200 ECO 1.92TB SSD",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 208 },
   "targets": [
    {
     "alias": "Sata1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\")FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata1' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unused_Rsvd_Blk_Cnt_Tot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Avg_Block-Erase_Count" }
     ]
    },
    {
     "alias": "Sata2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata2' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unused_Rsvd_Blk_Cnt_Tot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server2" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Current_Pending_Sector" }
     ]
    },
    {
     "alias": "Sata3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "synology_SMART_status2",
     "query": "SELECT distinct(\"RAW_value\") FROM \"synology_SMART_status2\" WHERE (\"disk_path\" = '/dev/sata3' AND \"nas_name\" = 'Server-Plex' AND \"smart_attribute\" = 'Unused_Rsvd_Blk_Cnt_Tot') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "RAW_value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "disk_path", "operator": "=", "value": "/dev/sata1" },
      { "condition": "AND", "key": "nas_name", "operator": "=", "value": "Server-Plex" },
      { "condition": "AND", "key": "smart_attribute", "operator": "=", "value": "Unused_Rsvd_Blk_Cnt_Tot" }
     ]
    }
   ]
  }
 ]
}